-- Clear existing data and start fresh
DELETE FROM menu_items;
DELETE FROM categories;
DELETE FROM cuisines;
DELETE FROM contact_messages;

-- Insert cuisines
INSERT INTO cuisines (name, slug, tagline, sort_order) VALUES
  ('Lebanese', 'lebanese', 'The table our family built', 1),
  ('Oriental', 'oriental', 'Grills, mezze, and slow-cooked rice', 2),
  ('Chinese', 'chinese', 'Wok-fired classics, done properly', 3),
  ('Italian', 'italian', 'Pasta and pizza, no shortcuts', 4),
  ('Sandwiches', 'sandwiches', 'Wraps, rolls, and handheld feasts', 5),
  ('Drinks', 'drinks', 'Refreshment for every mood', 6),
  ('Alcoholic Beverages', 'alcoholic-beverages', 'Wine, arak, and crafted cocktails', 7),
  ('Chicha', 'chicha', 'Hookah and shisha flavors', 8),
  ('Desserts', 'desserts', 'Sweet endings from four kitchens', 9);

-- Insert categories
INSERT INTO categories (cuisine_id, name)
SELECT id, 'Mezze' FROM cuisines WHERE slug = 'lebanese'
UNION ALL SELECT id, 'Grills' FROM cuisines WHERE slug = 'lebanese'
UNION ALL SELECT id, 'Bakery' FROM cuisines WHERE slug = 'lebanese'
UNION ALL SELECT id, 'Salads' FROM cuisines WHERE slug = 'lebanese'
UNION ALL SELECT id, 'Soups' FROM cuisines WHERE slug = 'lebanese'
UNION ALL SELECT id, 'Grills' FROM cuisines WHERE slug = 'oriental'
UNION ALL SELECT id, 'Rice & Grains' FROM cuisines WHERE slug = 'oriental'
UNION ALL SELECT id, 'Mezze' FROM cuisines WHERE slug = 'oriental'
UNION ALL SELECT id, 'Salads' FROM cuisines WHERE slug = 'oriental'
UNION ALL SELECT id, 'Soups' FROM cuisines WHERE slug = 'oriental'
UNION ALL SELECT id, 'Wok' FROM cuisines WHERE slug = 'chinese'
UNION ALL SELECT id, 'Small Plates' FROM cuisines WHERE slug = 'chinese'
UNION ALL SELECT id, 'Dim Sum' FROM cuisines WHERE slug = 'chinese'
UNION ALL SELECT id, 'Soups' FROM cuisines WHERE slug = 'chinese'
UNION ALL SELECT id, 'Rice & Noodles' FROM cuisines WHERE slug = 'chinese'
UNION ALL SELECT id, 'Pizza' FROM cuisines WHERE slug = 'italian'
UNION ALL SELECT id, 'Pasta' FROM cuisines WHERE slug = 'italian'
UNION ALL SELECT id, 'Risotto' FROM cuisines WHERE slug = 'italian'
UNION ALL SELECT id, 'Starters' FROM cuisines WHERE slug = 'italian'
UNION ALL SELECT id, 'Salads' FROM cuisines WHERE slug = 'italian'
UNION ALL SELECT id, 'Lebanese Wraps' FROM cuisines WHERE slug = 'sandwiches'
UNION ALL SELECT id, 'Oriental Wraps' FROM cuisines WHERE slug = 'sandwiches'
UNION ALL SELECT id, 'Chinese Wraps' FROM cuisines WHERE slug = 'sandwiches'
UNION ALL SELECT id, 'Italian Panini' FROM cuisines WHERE slug = 'sandwiches'
UNION ALL SELECT id, 'Fresh Juices' FROM cuisines WHERE slug = 'drinks'
UNION ALL SELECT id, 'Smoothies' FROM cuisines WHERE slug = 'drinks'
UNION ALL SELECT id, 'Hot Beverages' FROM cuisines WHERE slug = 'drinks'
UNION ALL SELECT id, 'Cold Beverages' FROM cuisines WHERE slug = 'drinks'
UNION ALL SELECT id, 'Traditional Drinks' FROM cuisines WHERE slug = 'drinks'
UNION ALL SELECT id, 'Milkshakes' FROM cuisines WHERE slug = 'drinks'
UNION ALL SELECT id, 'Lebanese Wines' FROM cuisines WHERE slug = 'alcoholic-beverages'
UNION ALL SELECT id, 'Arak' FROM cuisines WHERE slug = 'alcoholic-beverages'
UNION ALL SELECT id, 'Cocktails' FROM cuisines WHERE slug = 'alcoholic-beverages'
UNION ALL SELECT id, 'Beer' FROM cuisines WHERE slug = 'alcoholic-beverages'
UNION ALL SELECT id, 'Spirits' FROM cuisines WHERE slug = 'alcoholic-beverages'
UNION ALL SELECT id, 'Fruit Flavors' FROM cuisines WHERE slug = 'chicha'
UNION ALL SELECT id, 'Mint & Sweet' FROM cuisines WHERE slug = 'chicha'
UNION ALL SELECT id, 'Berry & Citrus' FROM cuisines WHERE slug = 'chicha'
UNION ALL SELECT id, 'Classic' FROM cuisines WHERE slug = 'chicha'
UNION ALL SELECT id, 'Premium' FROM cuisines WHERE slug = 'chicha'
UNION ALL SELECT id, 'Exotic' FROM cuisines WHERE slug = 'chicha'
UNION ALL SELECT id, 'Lebanese Sweets' FROM cuisines WHERE slug = 'desserts'
UNION ALL SELECT id, 'Oriental Sweets' FROM cuisines WHERE slug = 'desserts'
UNION ALL SELECT id, 'Chinese Sweets' FROM cuisines WHERE slug = 'desserts'
UNION ALL SELECT id, 'Italian Sweets' FROM cuisines WHERE slug = 'desserts'
UNION ALL SELECT id, 'Ice Cream' FROM cuisines WHERE slug = 'desserts'
UNION ALL SELECT id, 'Pastries' FROM cuisines WHERE slug = 'desserts';

-- Insert menu items
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan, is_featured) SELECT c.id, cat.id, 'Hummus Jebal', 'Slow-cooked chickpeas, tahini, olive oil, pine nuts.', 8.00, 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=400&h=300&fit=crop', true, true, true FROM cuisines c, categories cat WHERE c.slug = 'lebanese' AND cat.name = 'Mezze' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Tabbouleh', 'Finely chopped parsley, mint, tomato, bulgur.', 9.00, 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'lebanese' AND cat.name = 'Mezze' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Baba Ghanoush', 'Smoky roasted eggplant blended with tahini.', 8.50, 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'lebanese' AND cat.name = 'Mezze' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_featured) SELECT c.id, cat.id, 'Mixed Grill Jebal', 'Kafta, shish taouk, and lamb kebab.', 26.00, 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop', true FROM cuisines c, categories cat WHERE c.slug = 'lebanese' AND cat.name = 'Grills' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Shish Taouk', 'Yogurt-marinated chicken skewers, grilled.', 19.00, 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop' FROM cuisines c, categories cat WHERE c.slug = 'lebanese' AND cat.name = 'Grills' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Lamb Chops', 'Marinated lamb chops, grilled over charcoal.', 24.00, 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop' FROM cuisines c, categories cat WHERE c.slug = 'lebanese' AND cat.name = 'Grills' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Manakish Zaatar', 'Baked to order, thyme worked into the dough.', 7.00, 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'lebanese' AND cat.name = 'Bakery' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian) SELECT c.id, cat.id, 'Cheese Manakish', 'Akkar cheese, sesame, baked until golden.', 8.50, 'https://images.unsplash.com/photo-1558030006-450675393462?w=400&h=300&fit=crop', true FROM cuisines c, categories cat WHERE c.slug = 'lebanese' AND cat.name = 'Bakery' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Lentil Soup', 'Red lentils, onion, cumin, lemon.', 6.00, 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'lebanese' AND cat.name = 'Soups' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_featured) SELECT c.id, cat.id, 'Lamb Kabsa', 'Fragrant rice with tender lamb, raisins, almonds.', 22.00, 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop', true FROM cuisines c, categories cat WHERE c.slug = 'oriental' AND cat.name = 'Grills' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Chicken Mandi', 'Slow-cooked chicken with spiced rice.', 20.00, 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop' FROM cuisines c, categories cat WHERE c.slug = 'oriental' AND cat.name = 'Grills' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_featured) SELECT c.id, cat.id, 'Mixed Oriental Grill', 'Kafta, shish taouk, lamb chops, chicken.', 28.00, 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop', true FROM cuisines c, categories cat WHERE c.slug = 'oriental' AND cat.name = 'Grills' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Mujadara', 'Lentils, rice, and caramelized onions.', 14.00, 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'oriental' AND cat.name = 'Rice & Grains' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_spicy, is_featured) SELECT c.id, cat.id, 'Oriental Mezze Board', 'Six small plates for sharing.', 24.00, 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop', true, true, true FROM cuisines c, categories cat WHERE c.slug = 'oriental' AND cat.name = 'Mezze' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_spicy, is_featured) SELECT c.id, cat.id, 'Kung Pao Chicken', 'Roasted peanuts, dried chili, Sichuan heat.', 18.00, 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'chinese' AND cat.name = 'Wok' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_spicy) SELECT c.id, cat.id, 'Mapo Tofu', 'Silky tofu, minced pork, fermented beans.', 16.00, 'https://images.unsplash.com/photo-1582452919280-85adbc856546?w=400&h=300&fit=crop', true FROM cuisines c, categories cat WHERE c.slug = 'chinese' AND cat.name = 'Wok' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Sweet & Sour Chicken', 'Crisp-battered chicken, pineapple, bell pepper.', 17.00, 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop' FROM cuisines c, categories cat WHERE c.slug = 'chinese' AND cat.name = 'Wok' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Beef Chow Mein', 'High-heat noodles, char at the edges.', 17.00, 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop' FROM cuisines c, categories cat WHERE c.slug = 'chinese' AND cat.name = 'Wok' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Vegetable Dumplings', 'Hand-folded, pan-seared then steamed.', 12.00, 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'chinese' AND cat.name = 'Small Plates' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Spring Rolls', 'Crisp pastry with vegetables, glass noodles.', 10.00, 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'chinese' AND cat.name = 'Small Plates' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_featured) SELECT c.id, cat.id, 'Xiaolongbao', 'Soup dumplings with pork and rich broth.', 14.00, 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400&h=300&fit=crop', true FROM cuisines c, categories cat WHERE c.slug = 'chinese' AND cat.name = 'Dim Sum' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_featured) SELECT c.id, cat.id, 'Margherita Pizza', 'San Marzano tomato, fior di latte, basil.', 15.00, 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'italian' AND cat.name = 'Pizza' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian) SELECT c.id, cat.id, 'Pizza Quattro Formaggi', 'Mozzarella, gorgonzola, parmesan, fontina.', 17.00, 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop', true FROM cuisines c, categories cat WHERE c.slug = 'italian' AND cat.name = 'Pizza' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_spicy) SELECT c.id, cat.id, 'Diavola Pizza', 'Spicy salami, tomato, mozzarella, chili.', 16.00, 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop', true FROM cuisines c, categories cat WHERE c.slug = 'italian' AND cat.name = 'Pizza' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_featured) SELECT c.id, cat.id, 'Spaghetti Carbonara', 'Guanciale, egg, pecorino, black pepper.', 19.00, 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop', true FROM cuisines c, categories cat WHERE c.slug = 'italian' AND cat.name = 'Pasta' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian) SELECT c.id, cat.id, 'Pesto Genovese', 'Basil pesto, pine nuts, parmesan, trofie.', 18.00, 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400&h=300&fit=crop', true FROM cuisines c, categories cat WHERE c.slug = 'italian' AND cat.name = 'Pasta' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian) SELECT c.id, cat.id, 'Risotto ai Funghi', 'Carnaroli rice, wild mushroom, aged parmesan.', 19.00, 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400&h=300&fit=crop', true FROM cuisines c, categories cat WHERE c.slug = 'italian' AND cat.name = 'Risotto' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Bruschetta Trio', 'Tomato-basil, mushroom, white bean.', 11.00, 'https://images.unsplash.com/photo-1572441713132-51c75654db73?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'italian' AND cat.name = 'Starters' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_featured) SELECT c.id, cat.id, 'Shawarma Chicken Wrap', 'Marinated chicken, garlic toum, pickles.', 10.00, 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=300&fit=crop', true FROM cuisines c, categories cat WHERE c.slug = 'sandwiches' AND cat.name = 'Lebanese Wraps' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Shawarma Beef Wrap', 'Thinly sliced beef, tahini sauce, tomato.', 11.00, 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=300&fit=crop' FROM cuisines c, categories cat WHERE c.slug = 'sandwiches' AND cat.name = 'Lebanese Wraps' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Falafel Sandwich', 'Crispy falafel, tahini, tomato, pickled turnip.', 9.00, 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'sandwiches' AND cat.name = 'Lebanese Wraps' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Orange Juice', 'Freshly squeezed Valencia oranges.', 5.00, 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'drinks' AND cat.name = 'Fresh Juices' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Pomegranate Juice', 'Sweet pomegranate, a Lebanese favorite.', 6.00, 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'drinks' AND cat.name = 'Fresh Juices' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Mango Juice', 'Alphonso mango, creamy and tropical.', 6.00, 'https://images.unsplash.com/photo-1546173159-315724a31696?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'drinks' AND cat.name = 'Fresh Juices' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Lemonade', 'Fresh lemon, mint, sugar.', 4.00, 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'drinks' AND cat.name = 'Fresh Juices' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Turkish Coffee', 'Finely ground coffee, cardamom.', 4.00, 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'drinks' AND cat.name = 'Hot Beverages' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Sahlab', 'Warm milk, orchid powder, cinnamon, nuts.', 5.00, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'drinks' AND cat.name = 'Hot Beverages' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Jallab', 'Molasses, rose water, pine nuts, raisins.', 5.00, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'drinks' AND cat.name = 'Traditional Drinks' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian) SELECT c.id, cat.id, 'Chocolate Milkshake', 'Chocolate ice cream, milk, whipped cream.', 7.00, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop', true FROM cuisines c, categories cat WHERE c.slug = 'drinks' AND cat.name = 'Milkshakes' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Château Musar Red', 'Iconic Lebanese red, Bordeaux-style blend.', 65.00, 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'alcoholic-beverages' AND cat.name = 'Lebanese Wines' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Arak Touma', 'Triple-distilled, anise-flavored spirit.', 30.00, 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'alcoholic-beverages' AND cat.name = 'Arak' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Negroni', 'Gin, campari, vermouth.', 14.00, 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'alcoholic-beverages' AND cat.name = 'Cocktails' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Almaza Pilsner', 'Lebanese classic, crisp and refreshing.', 6.00, 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=300&fit=crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'alcoholic-beverages' AND cat.name = 'Beer' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Al Fakher Double Apple', 'Classic anise and apple, sweet and aromatic.', 15.00, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop' FROM cuisines c, categories cat WHERE c.slug = 'chicha' AND cat.name = 'Fruit Flavors' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Al Fakher Grape', 'Sweet Concord grape with mint undertones.', 15.00, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop' FROM cuisines c, categories cat WHERE c.slug = 'chicha' AND cat.name = 'Fruit Flavors' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Al Fakher Mango', 'Tropical mango, rich and fruity.', 15.00, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop' FROM cuisines c, categories cat WHERE c.slug = 'chicha' AND cat.name = 'Fruit Flavors' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Al Fakher Mint', 'Cool mint, refreshing classic.', 15.00, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop' FROM cuisines c, categories cat WHERE c.slug = 'chicha' AND cat.name = 'Mint & Sweet' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Starbuzz Blue Mist', 'Blueberry and mint, the flagship flavor.', 18.00, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop' FROM cuisines c, categories cat WHERE c.slug = 'chicha' AND cat.name = 'Mint & Sweet' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Al Fakher Cherry', 'Sweet cherry, rich and bold.', 15.00, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop' FROM cuisines c, categories cat WHERE c.slug = 'chicha' AND cat.name = 'Berry & Citrus' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Tangiers Noir Cane Mint', 'Intense mint, long-lasting.', 22.00, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop' FROM cuisines c, categories cat WHERE c.slug = 'chicha' AND cat.name = 'Premium' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_featured) SELECT c.id, cat.id, 'Baklava', 'Layered phyllo, walnuts, rose water syrup.', 8.00, 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=400&h=300&fit-crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'desserts' AND cat.name = 'Lebanese Sweets' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian) SELECT c.id, cat.id, 'Knafeh', 'Crispy semolina, sweet cheese, orange blossom syrup.', 9.00, 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=400&h=300&fit-crop', true FROM cuisines c, categories cat WHERE c.slug = 'desserts' AND cat.name = 'Lebanese Sweets' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian) SELECT c.id, cat.id, 'Maamoul', 'Date-filled semolina cookies, aromatic and buttery.', 7.00, 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=400&h=300&fit-crop', true FROM cuisines c, categories cat WHERE c.slug = 'desserts' AND cat.name = 'Lebanese Sweets' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Atayef', 'Stuffed pancakes with cream or nuts, fried and sweet.', 8.00, 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=400&h=300&fit-crop' FROM cuisines c, categories cat WHERE c.slug = 'desserts' AND cat.name = 'Lebanese Sweets' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian) SELECT c.id, cat.id, 'Muhallabia', 'Rose-scented milk pudding, elegant and silky.', 6.00, 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=400&h=300&fit-crop', true FROM cuisines c, categories cat WHERE c.slug = 'desserts' AND cat.name = 'Lebanese Sweets' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian) SELECT c.id, cat.id, 'Basbousa', 'Semolina cake, almond, coconut, syrup.', 6.00, 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=400&h=300&fit-crop', true FROM cuisines c, categories cat WHERE c.slug = 'desserts' AND cat.name = 'Oriental Sweets' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian, is_vegan) SELECT c.id, cat.id, 'Red Bean Soup', 'Sweet red bean, tangyuan in syrup.', 6.00, 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=400&h=300&fit-crop', true, true FROM cuisines c, categories cat WHERE c.slug = 'desserts' AND cat.name = 'Chinese Sweets' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_featured) SELECT c.id, cat.id, 'Tiramisu', 'Espresso, mascarpone, cocoa.', 9.00, 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit-crop', true FROM cuisines c, categories cat WHERE c.slug = 'desserts' AND cat.name = 'Italian Sweets' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Panna Cotta', 'Vanilla cream, berry compote.', 8.00, 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit-crop' FROM cuisines c, categories cat WHERE c.slug = 'desserts' AND cat.name = 'Italian Sweets' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Cannoli', 'Crisp shells, sweet ricotta, chocolate chips.', 8.00, 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit-crop' FROM cuisines c, categories cat WHERE c.slug = 'desserts' AND cat.name = 'Italian Sweets' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Gelato Trio', 'Three scoops: chocolate, pistachio, strawberry.', 7.00, 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit-crop' FROM cuisines c, categories cat WHERE c.slug = 'desserts' AND cat.name = 'Italian Sweets' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image, is_vegetarian) SELECT c.id, cat.id, 'Croissant', 'Buttery, flaky, French classic.', 4.00, 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit-crop', true FROM cuisines c, categories cat WHERE c.slug = 'desserts' AND cat.name = 'Pastries' AND cat.cuisine_id = c.id LIMIT 1;
INSERT INTO menu_items (cuisine_id, category_id, name, description, price, image) SELECT c.id, cat.id, 'Cheesecake', 'New York style, creamy and rich.', 8.00, 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit-crop' FROM cuisines c, categories cat WHERE c.slug = 'desserts' AND cat.name = 'Pastries' AND cat.cuisine_id = c.id LIMIT 1;
